service: app-bref

provider:
    name: aws
    region: eu-west-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    demo:
        handler: index.php
        description: 'lambda through Bref who simplifies php serverless'
        layers:
            - ${bref:layer.php-74}
